In [1]:
import numpy as np
a = np.array([1,2,3], dtype='int16')
b = np.array([[1,2,3,4,5], [6,7,8,9,0], [11,12,13,14,15]])

In [3]:
a.ndim
b.shape

(3, 5)

In [4]:
b.dtype
b

dtype('int32')

In [30]:
b[[0,0,1,2],[0,1,2,3]]
b[[1,2],[3,1]]
b[1:3,0:2]
b[(b>7) & (b<10)]

array([8, 9])

In [25]:
a.size

3

In [5]:
a.itemsize*a.size
# a.nbytes

6

In [31]:
b[:, -2]

array([ 4,  9, 14])

In [37]:
# fancy
b[:, 1:5:1]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9,  0],
       [12, 13, 14, 15]])

In [60]:
import random as r
array = np.array([[ [r.randint(0, 100) for col in range(2)] for col in range(2)] for row in range(3)])
print(array)

[[[64 59]
  [52 91]]

 [[69 47]
  [32 68]]

 [[65 80]
  [33 51]]]


In [62]:
array[:,1,1]

array([91, 68, 51])

In [96]:
ones = np.ones((5,5))
for i in range(1, 4):
    for j in range(1, 4):
        ones[i, j] = 0
ones[2,2] = 9
ones

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.full((2,2), r.randint(0,10))

array([[9, 9],
       [9, 9]])

In [74]:
np.full_like(a,4)

array([4, 4, 4], dtype=int16)

In [77]:
np.random.random_sample(a.shape)

array([0.43380035, 0.43367543, 0.04557359])

In [4]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
a = np.array([1,2,3], dtype='int16')
rep = np.repeat(a, 2, axis=0)
rep

array([1, 1, 2, 2, 3, 3], dtype=int16)

In [11]:
arr = np.arange(1,100000,1,dtype='int')
a = [1, 3, 6, 4, 1, 2]
a = [1, 2, 3]
a= [-1, -3]

# Codility Challenges

In [12]:
list(set(arr).difference(a))[0]

1

In [23]:
import numpy as np
def solution_array(a):
    # write your code in Python 3.6
    a=np.array(a)
    arr = np.arange(1,100000,1,dtype='int') 
    if np.where(np.logical_and(a>=-1000000, a<=1000000)):
        return list(set(arr).difference(a))[0]
    else:
        return None


In [24]:
solution([-1, -3])

1

In [45]:
def solution_list(a):
    # write your code in Python 3.6  
    lst = [*range(1, 1000000, 1)]
    if all(isinstance(x, int) for x in a) and (sorted(a)[0] > -1000000 and sorted(a)[-1]<1000000):
        return list(set(lst).difference(a))[0]
    else:
        return None

In [48]:
a= [1, 2, 3, 4, 5, 5, 7, 546, 1000001]
solution_list(a)
#np.where(np.logical_and(a>=-1000000, a<=1000000))

In [38]:
a=np.array(a)
lst = [*range(1, 1000000, 1)]
list(set(lst).difference(a))[0]

2

In [43]:
a= [1, 3,4,5,2,546,5,7]
sorted(a)

[1, 2, 3, 4, 5, 5, 7, 546]

In [58]:
a = [3,5,6,3,3,5]
z = []
for i in range(len(a)):
    for j in range(len(a)):
         if a[i]==a[j] and i!=j:
                c = [a[i],a[j]]
                z.append(c)
int(len(z)/2)
    

[[3, 3], [3, 3], [5, 5], [3, 3], [3, 3], [3, 3], [3, 3], [5, 5]]


In [61]:
def solution(a):
    # write your code in Python 3.6
    z = []
    for i in range(len(a)):
        for j in range(len(a)):
            if a[i]==a[j] and i!=j:
                    c = [a[i],a[j]]
                    z.append(c)
    return int(len(z)/2)


4

In [ ]:
-- write your code in PostgreSQL 9.4
SELECT distinct p1.name 
from participation p1 
JOIN participation AS p2 ON p1.name = p2.name AND p1.year = p2.year-1
JOIN participation AS p3 ON p1.name = p3.name AND p1.year = p3.year-2